"""RAG pipeline: index, retrieve, and inject armory content into LLM context."""

from harness.rag.chunker import (
    Chunk,
    ChunkStrategy,
    chunk_file,
    chunk_markdown,
    chunk_semantic,
    chunk_text,
)
from harness.rag.context import (
    EvidenceChunk,
    TurnEvidence,
    build_context,
    build_turn_evidence,
    estimate_tokens,
)
from harness.rag.index import (
    ArmoryIndex,
    build_index,
    iter_source_files,
    load_or_build,
    scan_unindexable_files,
)
from harness.rag.query_transform import (
    CompositeTransformer,
    HyDETransformer,
    IdentityTransformer,
    ModeSpecificQueryPlanner,
    ModeSpecificQueryTransformerProtocol,
    MultiQueryTransformer,
    PromptFn,
    QueryExpander,
    QueryTransformerProtocol,
    TransformStrategy,
    create_transformer,
    transform_query,
)
from harness.rag.retrieval_types import (
    EvidenceReference,
    RerankerProtocol,
    RetrieverProtocol,
    ScoredChunk,
)
from harness.rag.retrieve import (
    CrossEncoderReranker,
    DocumentBm25Retriever,
    EmbeddingRetriever,
    HybridRetriever,
    RetrievalMode,
    TfidfRetriever,
    retrieve,
)
from harness.rag.source_mapping import (
    SourceLineSpan,
    SourceMappingError,
    char_to_line,
    chunk_line_span,
    line_label,
    resolve_source_path,
    source_excerpt,
)

__all__ = [
    "ArmoryIndex",
    "Chunk",
    "ChunkStrategy",
    "CompositeTransformer",
    "CrossEncoderReranker",
    "DocumentBm25Retriever",
    "EmbeddingRetriever",
    "EvidenceChunk",
    "EvidenceReference",
    "HyDETransformer",
    "HybridRetriever",
    "IdentityTransformer",
    "ModeSpecificQueryPlanner",
    "ModeSpecificQueryTransformerProtocol",
    "MultiQueryTransformer",
    "PromptFn",
    "QueryExpander",
    "QueryTransformerProtocol",
    "RerankerProtocol",
    "RetrievalMode",
    "RetrieverProtocol",
    "ScoredChunk",
    "SourceLineSpan",
    "SourceMappingError",
    "TfidfRetriever",
    "TransformStrategy",
    "TurnEvidence",
    "build_context",
    "build_index",
    "build_turn_evidence",
    "char_to_line",
    "chunk_file",
    "chunk_line_span",
    "chunk_markdown",
    "chunk_semantic",
    "chunk_text",
    "create_transformer",
    "estimate_tokens",
    "iter_source_files",
    "line_label",
    "load_or_build",
    "resolve_source_path",
    "retrieve",
    "scan_unindexable_files",
    "source_excerpt",
    "transform_query",
]
