"""RAG pipeline: index, retrieve, and inject armory content into LLM context."""

from hephaistos.rag.chunker import (
    Chunk,
    ChunkStrategy,
    chunk_file,
    chunk_markdown,
    chunk_semantic,
    chunk_text,
)
from hephaistos.rag.context import (
    EvidenceChunk,
    TurnEvidence,
    build_context,
    build_turn_evidence,
    estimate_tokens,
)
from hephaistos.rag.index import ArmoryIndex, build_index, iter_source_files, load_or_build
from hephaistos.rag.query_transform import (
    CompositeTransformer,
    HyDETransformer,
    IdentityTransformer,
    MultiQueryTransformer,
    PromptFn,
    QueryExpander,
    QueryTransformerProtocol,
    TransformStrategy,
    create_transformer,
    transform_query,
)
from hephaistos.rag.retrieve import (
    CrossEncoderReranker,
    EmbeddingRetriever,
    HybridRetriever,
    RerankerProtocol,
    RetrieverProtocol,
    ScoredChunk,
    TfidfRetriever,
    retrieve,
)

__all__ = [
    "ArmoryIndex",
    "Chunk",
    "ChunkStrategy",
    "CompositeTransformer",
    "CrossEncoderReranker",
    "EmbeddingRetriever",
    "EvidenceChunk",
    "HyDETransformer",
    "HybridRetriever",
    "IdentityTransformer",
    "MultiQueryTransformer",
    "PromptFn",
    "QueryExpander",
    "QueryTransformerProtocol",
    "RerankerProtocol",
    "RetrieverProtocol",
    "ScoredChunk",
    "TfidfRetriever",
    "TransformStrategy",
    "TurnEvidence",
    "build_context",
    "build_index",
    "build_turn_evidence",
    "chunk_file",
    "chunk_markdown",
    "chunk_semantic",
    "chunk_text",
    "create_transformer",
    "estimate_tokens",
    "iter_source_files",
    "load_or_build",
    "retrieve",
    "transform_query",
]
