"""Low-level ANSI primitives shared by UI and infra layers.

This module exists so that ``hephaistos.logging`` (an infra module) can
use terminal colour helpers without importing from the ``app`` package.
Higher-level style composites live in ``hephaistos.terminal``.
"""

from __future__ import annotations

BOLD = "\033[1m"
DIM = "\033[2m"
RESET = "\033[0m"

BLACK = "#000000"
TRANSPARENT = "transparent"

# Theme roles:
# - brand is reserved for the Hephaistos wordmark and brand-only marks.
# - emphasis is for routine active labels and headings.
# - chrome_label is the single GHUI-style tint for status/sidebar labels and key hints.
# - chrome_detail is the darker companion tint for secondary labels and values.
# - composer_bar is the panel-gray input surface.
# - shortcut and metadata are compatibility aliases for the same chrome-label token.
# - accent is for semantic attention, warning, or action states.
HEPH_BRAND = "#C65050"
HEPH_CHROME_LABEL = "#D4C6A5"
HEPH_CHROME_DETAIL = "#948A73"
HEPH_METADATA = HEPH_CHROME_LABEL
HEPH_SELECTION_BACKGROUND = "#B85A5A"
TEXT_ON_HEPH_SELECTION = BLACK

FORGE_PANEL = "#1C1C1C"
FORGE_COMPOSER_BAR = FORGE_PANEL
FORGE_STONE = "#555555"
FORGE_TEXT = "#E0E0E0"
FORGE_DIM = "#808080"
FORGE_ACCENT = "#C8C8C8"
FORGE_EMPHASIS = FORGE_ACCENT
FORGE_CHROME_LABEL = HEPH_CHROME_LABEL
FORGE_CHROME_DETAIL = HEPH_CHROME_DETAIL
FORGE_METADATA = FORGE_CHROME_LABEL
FORGE_SHORTCUT = FORGE_CHROME_LABEL
FORGE_BRAND = HEPH_BRAND
FORGE_EMBER = FORGE_BRAND
FORGE_CONFIGURED = "#7F9A6A"
FORGE_ERROR = "#CC3333"
FORGE_SUCCESS = "#66BB6A"
FORGE_HIGHLIGHT = "#333333"
FORGE_SELECTION_BACKGROUND = HEPH_SELECTION_BACKGROUND
FORGE_SELECTION_TEXT = TEXT_ON_HEPH_SELECTION
FORGE_MATERIAL_ENABLED = FORGE_CONFIGURED
FORGE_MATERIAL_DISABLED = HEPH_BRAND

LIGHT_PANEL = "#EDE8DC"
LIGHT_STONE = "#C4B8A6"
LIGHT_TEXT = "#2C241B"
LIGHT_DIM = "#7A7068"
LIGHT_ACCENT = "#8A5A2B"
LIGHT_EMPHASIS = LIGHT_TEXT
LIGHT_CHROME_LABEL = "#8F5F5F"
LIGHT_CHROME_DETAIL = "#674545"
LIGHT_COMPOSER_BAR = LIGHT_PANEL
LIGHT_METADATA = LIGHT_CHROME_LABEL
LIGHT_SHORTCUT = LIGHT_CHROME_LABEL
LIGHT_BRAND = HEPH_BRAND
LIGHT_EMBER = LIGHT_BRAND
LIGHT_CONFIGURED = "#6D804F"
LIGHT_ERROR = "#B03A2E"
LIGHT_SUCCESS = "#2E8B57"
LIGHT_HIGHLIGHT = "#D4C9B8"
LIGHT_SELECTION_BACKGROUND = HEPH_SELECTION_BACKGROUND
LIGHT_SELECTION_TEXT = TEXT_ON_HEPH_SELECTION
LIGHT_MATERIAL_ENABLED = LIGHT_CONFIGURED
LIGHT_MATERIAL_DISABLED = HEPH_BRAND

HIGH_CONTRAST_PANEL = "#1A1A1A"
HIGH_CONTRAST_STONE = "#2E2E2E"
HIGH_CONTRAST_TEXT = "#FFFFFF"
HIGH_CONTRAST_DIM = "#C0C0C0"
HIGH_CONTRAST_ACCENT = "#FFD400"
HIGH_CONTRAST_EMPHASIS = HIGH_CONTRAST_TEXT
HIGH_CONTRAST_CHROME_LABEL = HIGH_CONTRAST_DIM
HIGH_CONTRAST_CHROME_DETAIL = "#8A8A8A"
HIGH_CONTRAST_COMPOSER_BAR = HIGH_CONTRAST_PANEL
HIGH_CONTRAST_METADATA = HIGH_CONTRAST_CHROME_LABEL
HIGH_CONTRAST_SHORTCUT = HIGH_CONTRAST_CHROME_LABEL
HIGH_CONTRAST_BRAND = HEPH_BRAND
HIGH_CONTRAST_EMBER = HIGH_CONTRAST_BRAND
HIGH_CONTRAST_CONFIGURED = "#A9C97A"
HIGH_CONTRAST_ERROR = "#FF4D4D"
HIGH_CONTRAST_SUCCESS = "#00FF88"
HIGH_CONTRAST_HIGHLIGHT = "#404040"
HIGH_CONTRAST_SELECTION_BACKGROUND = HEPH_SELECTION_BACKGROUND
HIGH_CONTRAST_SELECTION_TEXT = TEXT_ON_HEPH_SELECTION
HIGH_CONTRAST_MATERIAL_ENABLED = HIGH_CONTRAST_CONFIGURED
HIGH_CONTRAST_MATERIAL_DISABLED = HEPH_BRAND

# Backwards-compatible forge names used by lower-level logging code.
FORGE_ASH = FORGE_TEXT
FORGE_SMOKE = FORGE_DIM
FORGE_IRON = FORGE_ERROR
FORGE_GREEN = FORGE_SUCCESS


def ansi_fg(hex_color: str) -> str:
    """Return a truecolor ANSI foreground sequence for a hex color."""
    color = hex_color.lstrip("#")
    r = int(color[0:2], 16)
    g = int(color[2:4], 16)
    b = int(color[4:6], 16)
    return f"\033[38;2;{r};{g};{b}m"
