"""Public SDK surface for embedding Heph in other runtimes."""

from __future__ import annotations

from heph.sdk.capabilities import (
    JSONL_ERROR_CODES,
    JSONL_MESSAGE_SPECS,
    JSONL_MESSAGE_TYPES,
    JSONL_REQUEST_SPEC,
    SDK_CAPABILITIES,
    SDK_CAPABILITIES_VERSION,
    HephSdkCapabilities,
    get_sdk_capabilities,
    validate_sdk_capabilities,
)
from heph.sdk.events import (
    AssistantDelta,
    CompactRequest,
    Guardrail,
    HephEvent,
    MaterialOperation,
    Notice,
    ReasoningDelta,
    ToolCall,
    ToolResult,
    TurnComplete,
    event_to_dict,
    from_turn_event,
)
from heph.sdk.factory import (
    CreateHephRuntimeResult,
    CreateHephServiceResult,
    CreateHephSessionResult,
    HephSdkOptions,
    create_chat_config,
    create_heph_runtime,
    create_heph_service,
    create_heph_session,
)
from heph.sdk.materials import (
    ExtractionHealthIssueSummary,
    ExtractionHealthSummary,
    ImportMaterialsSummary,
    IndexProgressEvent,
    IndexSummary,
    MaterialSummary,
)
from heph.sdk.models import ModelChoiceSummary
from heph.sdk.providers import ProviderSummary
from heph.sdk.runtime import (
    ArmorySummary,
    ArmoryValidationSummary,
    HephEventListener,
    HephMessage,
    HephRuntime,
    HephSdkBusyError,
    HephSdkError,
    HephSession,
    SessionSummary,
)
from heph.sdk.service import HephService, ServicePayload, ServiceStream
from heph.sdk.settings import (
    SDK_MUTABLE_APP_SETTINGS,
    PrivacySettingsSummary,
    SdkAppSettings,
    SdkSettingsError,
    SettingChoice,
    SettingsChoices,
    load_sdk_app_settings,
    update_sdk_app_settings,
)
from heph.sdk.state import (
    HephSdkRuntimeState,
    HephSdkServiceState,
    HephSdkSessionState,
    HephSdkState,
)
from heph.sdk.stdio import (
    SDK_JSONL_PROTOCOL,
    SDK_JSONL_VERSION,
    JsonlSdkServer,
    SdkProtocolError,
    serve_stdio,
)

__all__ = [
    "JSONL_ERROR_CODES",
    "JSONL_MESSAGE_SPECS",
    "JSONL_MESSAGE_TYPES",
    "JSONL_REQUEST_SPEC",
    "SDK_CAPABILITIES",
    "SDK_CAPABILITIES_VERSION",
    "SDK_JSONL_PROTOCOL",
    "SDK_JSONL_VERSION",
    "SDK_MUTABLE_APP_SETTINGS",
    "ArmorySummary",
    "ArmoryValidationSummary",
    "AssistantDelta",
    "CompactRequest",
    "CreateHephRuntimeResult",
    "CreateHephServiceResult",
    "CreateHephSessionResult",
    "ExtractionHealthIssueSummary",
    "ExtractionHealthSummary",
    "Guardrail",
    "HephEvent",
    "HephEventListener",
    "HephMessage",
    "HephRuntime",
    "HephSdkBusyError",
    "HephSdkCapabilities",
    "HephSdkError",
    "HephSdkOptions",
    "HephSdkRuntimeState",
    "HephSdkServiceState",
    "HephSdkSessionState",
    "HephSdkState",
    "HephService",
    "HephSession",
    "ImportMaterialsSummary",
    "IndexProgressEvent",
    "IndexSummary",
    "JsonlSdkServer",
    "MaterialOperation",
    "MaterialSummary",
    "ModelChoiceSummary",
    "Notice",
    "PrivacySettingsSummary",
    "ProviderSummary",
    "ReasoningDelta",
    "SdkAppSettings",
    "SdkProtocolError",
    "SdkSettingsError",
    "ServicePayload",
    "ServiceStream",
    "SessionSummary",
    "SettingChoice",
    "SettingsChoices",
    "ToolCall",
    "ToolResult",
    "TurnComplete",
    "create_chat_config",
    "create_heph_runtime",
    "create_heph_service",
    "create_heph_session",
    "event_to_dict",
    "from_turn_event",
    "get_sdk_capabilities",
    "load_sdk_app_settings",
    "serve_stdio",
    "update_sdk_app_settings",
    "validate_sdk_capabilities",
]
